import React from 'react'

const App = () => {
    return (
        <div style={{
            padding: 40
        }}>
            <h1 className='header'>Hello World</h1>
            <h2>This is a react app generated by Fasta</h2>
            <p>Happy Coding!!!</p>
        </div>
    )
}

export default App
